services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: 11
      USERNAME: "CFilho"
      PASSWORD: "admin@654321"
      LANGUAGE: "Portuguese"
      REGION: "pt-BR"
      KEYBOARD: "pt-BR"
      RAM_SIZE: "12G"
      CPU_CORES: 4
      DISK_SIZE: "256G"
      VIDEO_WIDTH: 1920
      VIDEO_HEIGHT: 1080
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m